version: "3"
services:
  hub:
    image: selenium/hub:4.5.0
    ports:
      - "80:4444"
  chrome:
    image: selenium/node-chrome:4.5.0
    shm_size: '2g'
    depends_on:
      - hub
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
