pipeline {
  agent {
       label 'java'
  }
  environment{
    NUMBER = 3
  }
  stages {
    stage('stage-1') {
      steps {
        echo "doing mvn clean"
        echo "doing mvn package"
        echo "Number=${NUMBER}"
      }
    }

    stage('stage-2') {
     environment{
        NUMBER = 6
      }
      steps {
        echo "building docker image"
        echo "Number=${NUMBER}"
      }
    }

    stage('stage-3') {
      steps {
        echo "publishing docker image"
      }
    }
  }

  post {
    always {
      echo "doing clean up"
    }
  }
}
