version: "3"
services:
  google-test:
    image: vinsdocker/selenium
    environment:
      - BROWSER=${BROWSER}
      - HUB_HOST=hub
      - THREAD_COUNT=2
      - TEST_SUITE=testng.xml
    volumes:
      - ./output/vendor-portal:/home/selenium-docker/test-output
  demo-test:
    image: vinsdocker/selenium
    environment:
      - BROWSER=${BROWSER}
      - HUB_HOST=hub
      - THREAD_COUNT=2
      - TEST_SUITE=testng.xml
    volumes:
      - ./output/vendor-portal:/home/selenium-docker/test-output

